import os
from PIL import Image

def process_ui():
    INPUT_PATH = r"c:\Users\mirtg\OneDrive\Escritorio\Cristobalini\code related\Tamagotchi\apps\web\public\assets\retro_ui_icons_1768544742647.png"
    OUTPUT_PATH = r"c:\Users\mirtg\OneDrive\Escritorio\Cristobalini\code related\Tamagotchi\apps\web\public\assets\ui_icons_strip.png"

    if not os.path.exists(INPUT_PATH):
        print("Input not found")
        return

    print(f"Processing {INPUT_PATH}...")
    img = Image.open(INPUT_PATH).convert("RGBA")

    # Background removal
    bg_color = (203, 205, 204)
    threshold = 20

    datas = img.getdata()
    new_data = []
    for item in datas:
        if abs(item[0] - bg_color[0]) < threshold and \
           abs(item[1] - bg_color[1]) < threshold and \
           abs(item[2] - bg_color[2]) < threshold:
            new_data.append((255, 255, 255, 0)) # Transparent
        else:
            new_data.append(item)
    img.putdata(new_data)

    # Grid Logic:
    # Since blob detection failed, let's assume a 3x3 grid or similar layout if it was generated by AI.
    # Actually, let's try to detect rows again but with better logging.
    # Or, crop fixed regions if we can guess.

    # Alternative: Scan again but print what it sees.
    # The file size is 1024x1024. If it has 9 icons, they might be arranged in a 3x3 grid,
    # effectively filling the space or centered in cells.
    # Let's try 3x3 cells of 341x341.

    rows = 3
    cols = 3
    cell_w = 1024 // cols
    cell_h = 1024 // rows

    icons = []

    for r in range(rows):
        for c in range(cols):
            x = c * cell_w
            y = r * cell_h
            # Crop cell
            cell = img.crop((x, y, x + cell_w, y + cell_h))
            bbox = cell.getbbox()
            if bbox:
                # Found something in this cell
                # Ensure it's not just noise
                if (bbox[2] - bbox[0]) > 10 and (bbox[3] - bbox[1]) > 10:
                    icon = cell.crop(bbox)
                    icons.append(icon)
                    print(f"Found icon at {r},{c} size {icon.size}")

    print(f"Found {len(icons)} icons via grid search.")

    if len(icons) > 0:
        ICON_SIZE = 24
        strip_w = len(icons) * ICON_SIZE
        strip_h = ICON_SIZE
        strip = Image.new("RGBA", (strip_w, strip_h), (0,0,0,0))

        for i, icon in enumerate(icons):
            # Scale to strictly 24x24
            # Or preserve aspect ratio
             w, h = icon.size
             scale = min(ICON_SIZE/w, ICON_SIZE/h) * 0.9
             new_w = int(w * scale)
             new_h = int(h * scale)
             icon_resized = icon.resize((new_w, new_h), Image.Resampling.NEAREST)

             target_x = i * ICON_SIZE + (ICON_SIZE - new_w) // 2
             target_y = (ICON_SIZE - new_h) // 2

             strip.paste(icon_resized, (target_x, target_y))

        strip.save(OUTPUT_PATH)
        print(f"Saved strip to {OUTPUT_PATH}")

if __name__ == "__main__":
    process_ui()
